### ISSUE TITLE
Cannot extract marks from a PDF file that have a different template

### ISSUE THREAD

**Issue by akhateeb22** [Rami-Sabbagh/OurMarks#107]
I faced a problem In extracting marks from the PDF file which I will leave It below, It gave me null for all students' marks.
PDF file:
[Compiler_Project.pdf](https://github.com/Rami-Sabbagh/OurMarks/files/9448027/Compiler_Project.pdf)
JSON file I got after converting:
[Compiler_Project.txt](https://github.com/Rami-Sabbagh/OurMarks/files/9448068/Compiler_Project.txt)
It's a problem related to the way of reading the PDF file and extracting the marks.

**Comment by Rami-Sabbagh** [comment]
Hey there, thanks for reporting the issue!
Unfortunately I'm busy in the current few months, so I'm unsure if I can find some time to donate for this project.

Collecting those PDFs with errors is good so that when I find some time I could solve them all in one go.

**Comment by Rami-Sabbagh** [comment]
Also feel totally free to fork the project and fix the issue yourself!
But be sure to keep it open-source as required by the AGPL-3.0 license.

You can later create a pull request and I would be happy to review and merge it, so everyone could benefit.

**Comment by Rami-Sabbagh** [comment]
Fixed in 51baf0bba9db6331edcde6d96661ad3b3c7daffd and available in the 3.0.0 release of the library.

Please reopen the issue if it still persists after upgrading.
